export const todosState = {
  allIds: [1, 2, 3, 4, 5, 6, 7, 8],
  byId: {
    1: {
      id: 1,
      completed: false,
      description: 'Send email',
      leadId: 1,
      priority_rank: 1,
      status: 'Follow Up',
    },
    2: {
      id: 2,
      completed: false,
      description: 'Send Email',
      leadId: 2,
      priority_rank: 2,
      status: 'Follow Up',
    },
    3: {
      id: 3,
      completed: false,
      description: 'Create engagement letter',
      leadId: 3,
      priority_rank: 3,
      status: 'Follow Up',
    },
    4: {
      id: 4,
      completed: false,
      description: 'Do a thing',
      leadId: 4,
      priority_rank: 4,
      status: 'With Client',
    },
    5: {
      id: 5,
      completed: false,
      description: 'Do a thing',
      leadId: 5,
      priority_rank: 5,
      status: 'With Client',
    },
    6: {
      id: 6,
      completed: false,
      description: 'Do a thing',
      leadId: 6,
      priority_rank: 6,
      status: 'Follow Up',
    },
    7: {
      id: 7,
      completed: false,
      description: 'Do a thing',
      leadId: 7,
      priority_rank: 7,
      status: 'Follow Up',
    },
    8: {
      id: 8,
      completed: false,
      description: 'Do a thing',
      leadId: 8,
      priority_rank: 8,
      status: 'Follow Up',
    },
    9: {
      id: 9,
      completed: false,
      description: 'Do a thing',
      leadId: 9,
      priority_rank: 9,
      status: 'Follow Up',
    },
  },
};
